// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr74IiRHT9dbcj3hDtD5II3tFbisiM8CM',
    appId: '1:80681955172:web:9ebcd4e1bda4e21142d471',
    messagingSenderId: '80681955172',
    projectId: 'jarnama-app-43f9f',
    authDomain: 'jarnama-app-43f9f.firebaseapp.com',
    storageBucket: 'jarnama-app-43f9f.appspot.com',
    measurementId: 'G-YLFB5MDC2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdzYQeSIIeh626ihsnnMqKHkbxCGGB6bE',
    appId: '1:80681955172:android:146ed3d3527b769842d471',
    messagingSenderId: '80681955172',
    projectId: 'jarnama-app-43f9f',
    storageBucket: 'jarnama-app-43f9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQBcRHYS62kPEIDgjyQM_0GTOcC_eydqQ',
    appId: '1:80681955172:ios:07b1f98aa560e9d242d471',
    messagingSenderId: '80681955172',
    projectId: 'jarnama-app-43f9f',
    storageBucket: 'jarnama-app-43f9f.appspot.com',
    iosClientId: '80681955172-qrs8cre6r284f5vfd8d0i0r7g1o8gr80.apps.googleusercontent.com',
    iosBundleId: 'com.example.jarnamaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQBcRHYS62kPEIDgjyQM_0GTOcC_eydqQ',
    appId: '1:80681955172:ios:07b1f98aa560e9d242d471',
    messagingSenderId: '80681955172',
    projectId: 'jarnama-app-43f9f',
    storageBucket: 'jarnama-app-43f9f.appspot.com',
    iosClientId: '80681955172-qrs8cre6r284f5vfd8d0i0r7g1o8gr80.apps.googleusercontent.com',
    iosBundleId: 'com.example.jarnamaApp',
  );
}
